### ISSUE TITLE
Explain api_url

### ISSUE THREAD

**Issue by jibranmazhar** [reveal-co/django-json-api#28]
Hello guys,
Please upload running example in your repo i did not get it. because i dont know how to expose api_url to model. i got Http 404 error please help me thanks in advance.

**Comment by phantom-as** [comment]
@jibranmazhar you need to declare your remote model as a python class and configure this class's ```Meta``` to hold the base URL value.

Let us say you want to consume the resource at "https://my.domain.com/api/records/", in that case:
- the ```api_url``` value should be "https://my.domain.com/api/"
- the ```resource_type``` should be "records"

So your class would look like this:
```python

from django_json_api.models import JSONAPIModel
from django_json_api.fields import Attribute

class Record(JSONAPIModel):
    class Meta:
        api_url = 'https://my.domain.com/api/'
        resource_type = 'records'

    ... declare attributes and relationships here ...

```

The example in the readme does exactly that, except the it uses a variable instead of a hard coded string (```MICROSERVICE_A_API_URL```)

I hope it helps!

**Comment by jibranmazhar** [comment]
Thanks you so much i understand now what you saying

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
